# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_LINK: cG9zdGdyZXNxbDovL215YXBwX3VzZXI6bXlhcHBfcGFzc3dvcmRAaG9zdC5taW5pa3ViZS5pbnRlcm5hbDo1NDMyL215YXBwX2Ri
